#!/bin/bash

STORE_PASSWORD=pado-web
echo "password=$STORE_PASSWORD"

# parseFileName parses file names found in the lib directory
# to drop the version postfix from the select files names.
# arg1 fileName - file name
# arg2 delimiterCount - delimiter count of postfix for determining the index number
function parseFileName
{
   local FILE_NAME=$1	   
   local DELIMITER_COUNT=$2	   
   IFS='-'; vector=($FILE_NAME); unset IFS;   
   let LAST_INDEX=${#vector[@]}-1
   let FILE_HEAD_LAST_INDEX=LAST_INDEX-DELIMITER_COUNT
   FILE_HEAD=
   for (( i = 0; i <= ${FILE_HEAD_LAST_INDEX}; i++ ))
   do
      if [ $i == 0 ]; then
         FILE_HEAD=${vector[$i]}
      else 
         FILE_HEAD=$FILE_HEAD-${vector[$i]}
      fi
   done

   if [ "%FILE_HEAD%" != "" ]; then
      mv -f $FILE_NAME $FILE_HEAD.jar
   fi
}

# Drop the version postfix from the pado jar file names.
pushd lib > /dev/null 2>&1
for file in pado-*.jar
do
   parseFileName $file 2
done

# Drop the version postif from the gemfire jar file names.
for file in gemfire-*.jar
do
   parseFileName $file 1
done
popd > /dev/null 2>&1

if [ ! -d slib/naf ]; then
  mkdir -p slib/naf
fi
if [ ! -d slib/app ]; then
  mkdir -p slib/app
fi

# lib/*.jar
if [ -d lib ]; then
   JAR_FILES=`ls lib/*.jar` > /dev/null 2>&1
   for i in $JAR_FILES; do
      echo "$i"
      jarsigner -keystore pado-web.keystore -storepass $STORE_PASSWORD -tsa http://timestamp.digicert.com -signedjar s$i $i pado-web
      #jarsigner -keystore pado-web.keystore -storepass $STORE_PASSWORD -signedjar s$i $i pado-web > /dev/null 2>&1
   done
fi

# lib/naf/*.jar
if [ -d lib/naf ]; then
   JAR_FILES=`ls lib/naf/*.jar` > /dev/null 2>&1
   for i in $JAR_FILES; do
      echo "$i"
      jarsigner -keystore pado-web.keystore -storepass $STORE_PASSWORD -tsa http://timestamp.digicert.com -signedjar s$i $i pado-web
      #jarsigner -keystore pado-web.keystore -storepass $STORE_PASSWORD -signedjar s$i $i pado-web > /dev/null 2>&1
   done
fi

# lib/app/*.jar
if [ -d lib/app ]; then
   JAR_FILES=`ls lib/app/*.jar` > /dev/null 2>&1
   for i in $JAR_FILES; do
      echo "$i"
      jarsigner -keystore pado-web.keystore -storepass $STORE_PASSWORD -tsa http://timestamp.digicert.com -signedjar s$i $i pado-web
      #jarsigner -keystore pado-web.keystore -storepass $STORE_PASSWORD -signedjar s$i $i pado-web > /dev/null 2>&1
   done
fi

# etc.jar
echo "etc.jar"
#jar cvfm etc.jar MANIFEST.MF etc
jar cvf etc.jar etc
jarsigner -keystore pado-web.keystore -storepass $STORE_PASSWORD -tsa http://timestamp.digicert.com -signedjar setc.jar etc.jar pado-web
#jarsigner -keystore pado-web.keystore -storepass $STORE_PASSWORD -signedjar setc.jar etc.jar pado-web > /dev/null 2>&1

# sec.jar
echo "sec.jar"
#jar cvfm sec.jar MANIFEST.MF security
jar cvf sec.jar security
jarsigner -keystore pado-web.keystore -storepass $STORE_PASSWORD -tsa http://timestamp.digicert.com -signedjar ssec.jar sec.jar pado-web
#jarsigner -keystore pado-web.keystore -storepass $STORE_PASSWORD -signedjar ssec.jar sec.jar pado-web > /dev/null 2>&1

